

//*COSTS

//SET
export const SET_COSTS_DATE = "SET_COSTS_DATE";



//*MODAL MESSAGE

export const SHOW_MODAL_MESSAGE = "SHOW_MODAL_MESSAGE";
export const HIDE_MODAL_MESSAGE = "HIDE_MODAL_MESSAGE";
export const SHOW_LOGOUT_MODAL = "SHOW_LOGOUT_MODAL";
export const HIDE_LOGOUT_MODAL = "HIDE_LOGOUT_MODAL";
export const SET_MODAL_MESSAGE_HEADER = "SET_MODAL_MESSAGE_HEADER";
export const SET_DISPUTED_SIA_COUNT_MODAL = "SET_DISPUTED_SIA_COUNT_MODAL";
export const SET_DISPUTED_CC_COUNT_MODAL = "SET_DISPUTED_CC_COUNT_MODAL";

//*REPORT

//GET

export const GET_COSTS_ACTIVITY_DAILY = "GET_COSTS_ACTIVITY_DAILY";
export const GET_COSTS_ACTIVITY_WEEKLY = "GET_COSTS_ACTIVITY_WEEKLY";
export const GET_COSTS_ACTIVITY_MONTHLY = "GET_COSTS_ACTIVITY_MONTHLY";

//SET
export const SET_RECEIPT_DATA = "SET_RECEIPT_DATA";

//*MODAL PROMPT
export const SHOW_MODAL_PROMPT = "SHOW_MODAL_PROMPT";
export const HIDE_MODAL_PROMPT = "HIDE_MODAL_PROMPT";
export const SET_DISPUTED_NOTE = "SET_DISPUTED_NOTE";
export const SET_DISPUTED_PAYMENT_ID = "SET_DISPUTED_PAYMENT_ID";
export const RESET_MODAL_ACTIVITY = "RESET_MODAL_ACTIVITY";

//*MODAL ACTION
export const SHOW_ACTION_MODAL = "SHOW_ACTION_MODAL";
export const HIDE_ACTION_MODAL = "HIDE_ACTION_MODAL";

//*AUTHORISE

//GET
export const GET_AUTHORISE_DOORSTAFF = "GET_AUTHORISE_DOORSTAFF";
export const GET_AUTHORISE_COSTS = "GET_AUTHORISE_COSTS";

//CHECK
export const CHECK_AUTHORISE_DOORSTAFF = "CHECK_AUTHORISE_DOORSTAFF";
export const CHECK_AUTHORISE_COSTS = "CHECK_AUTHORISE_COSTS";
export const CHECK_ALL_AUTHORISE_DOORSTAFF = "CHECK_ALL_AUTHORISE_DOORSTAFF";
export const CHECK_ALL_AUTHORISE_COSTS = "CHECK_ALL_AUTHORISE_COSTS";

//UNCHECK
export const UNCHECK_AUTHORISE_DOORSTAFF = "UNCHECK_AUTHORISE_DOORSTAFF";
export const UNCHECK_AUTHORISE_COSTS = "UNCHECK_AUTHORISE_COSTS";
export const UNCHECK_ALL_AUTHORISE_DOORSTAFF =
  "UNCHECK_ALL_AUTHORISE_DOORSTAFF";
export const UNCHECK_ALL_AUTHORISE_COSTS = "UNCHECK_ALL_AUTHORISE_COSTS";

//*SEARCH

//GET
export const GET_ACTIVITIES_SEARCH_LOCATIONS_GROUP_OPT =
  "GET_ACTIVITIES_SEARCH_LOCATIONS_GROUP_OPT";
export const GET_ACTIVITIES_SEARCH_SUPPLIERS_OPT =
  "GET_ACTIVITIES_SEARCH_SUPPLIERS_OPT";
export const GET_ACTIVITIES_SEARCH_PAYMENT_STATUS_GROUP_OPT =
  "GET_ACTIVITIES_SEARCH_PAYMENT_STATUS_GROUP_OPT";
export const GET_ACTIVITIES_SEARCH_LOCATIONS_OPT =
  "GET_ACTIVITIES_SEARCH_LOCATIONS_OPT";
export const GET_ACTIVITIES_SEARCH_PAYMENT_STATUS_OPT =
  "GET_ACTIVITIES_SEARCH_PAYMENT_STATUS_OPT";
export const GET_ACTIVITIES_SEARCH_STAFF_OPT =
  "GET_ACTIVITIES_SEARCH_STAFF_OPT";
export const GET_SEARCHED_ACTIVITES = "GET_SEARCHED_ACTIVITES";
export const GET_SEARCHED_COSTS = "GET_SEARCHED_COSTS";

//SET
export const SET_ACTIVITIES_SEARCH_FROM_DATE =
  "SET_ACTIVITIES_SEARCH_FROM_DATE";
export const SET_ACTIVITIES_SEARCH_TO_DATE = "SET_ACTIVITIES_SEARCH_TO_DATE";

//*HISTORY

//GET
export const GET_HISTORY_AUDIT_TYPE_OPT = "GET_HISTORY_AUDIT_TYPE_OPT";
export const GET_HISTORY_AUDIT_LOCATIONS_OPT =
  "GET_HISTORY_AUDIT_LOCATIONS_OPT";
export const GET_HISTORY_AUDIT_STAFF_OPT = "GET_HISTORY_AUDIT_STAFF_OPT";
export const GET_HISTORY_AUDIT_USER_OPT = "GET_HISTORY_AUDIT_USER_OPT";

//SET
export const SET_HISTORY_AUDIT_FROM_DATE = "SET_HISTORY_AUDIT_FROM_DATE";
export const SET_HISTORY_AUDIT_TO_DATE = "SET_HISTORY_AUDIT_TO_DATE";

//*LOADER

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

//*LOGIN

export const LOGIN = "LOGIN";
export const LOGOFF = "LOGOFF";
export const SHOW_ERROR_ON_LOGIN = "SHOW_ERROR_ON_LOGIN";
export const CLEAR_ERROR_ON_LOGIN = "CLEAR_ERROR_ON_LOGIN";

//* ANALYTICS

//AREA MANAGER
export const GET_AREA_MANAGER_ANALYTICS_LOCATIONS =
  "GET_AREA_MANAGER_ANALYTICS_LOCATIONS";
export const TOGGLE_ARREA_MANAGER_ANALYTICS_LOCATIONS =
  "TOGGLE_ARREA_MANAGER_ANALYTICS_LOCATIONS";
export const GET_AREA_MANAGER_ANALYTICS_COSTS =
  "GET_AREA_MANAGER_ANALYTICS_COSTS";
export const GET_AREA_MANAGER_ANALYTICS_DOORSTAFF =
  "GET_AREA_MANAGER_ANALYTICS_DOORSTAFF";
export const SET_AREA_MANAGER_ANALYTICS_DATE_FROM =
  "SET_AREA_MANAGER_ANALYTICS_DATE_FROM";
export const SET_AREA_MANAGER_ANALYTICS_DATE_TO =
  "SET_AREA_MANAGER_ANALYTICS_DATE_TO";

//PUB MANAGER
export const GET_DOORSTAFF_ANALYTICS = "GET_DOORSTAFF_ANALYTICS";
export const GET_COSTS_ANALYTICS = "GET_COSTS_ANALYTICS";
