export const GET_ACTIVITY_TYPE_OPT = "GET_ACTIVITY_TYPE_OPT";
export const GET_ACTIVITY_SUPPLIER_OPT = "GET_ACTIVITY_SUPPLIER_OPT";
export const GET_ACTIVITY_RATE = "GET_ACTIVITY_RATE";
export const GET_CURRENT_ACTIVITY = "GET_CURRENT_ACTIVITY";
export const GET_RECENT_ACTIVITY = "GET_RECENT_ACTIVITY";
export const GET_DISPUTED_ACTIVITY = "GET_DISPUTED_ACTIVITY";
export const GET_DISPUTED_COUNT = "GET_DISPUTED_COUNT";

//SET
export const SET_ACTIVITY_TYPE = "SET_ACTIVITY_TYPE";
export const SET_ACTIVITY_SUPPLIER = "SET_ACTIVITY_SUPPLIER";
export const SET_ACTIVITY_HOURS_WORKED = "SET_ACTIVITY_HOURS_WORKED";
export const SET_ACTIVITY_COST_VALUE = "SET_ACTIVITY_COST_VALUE";
export const CLEAR_ACTIVITY = "CLEAR_ACTIVITY";

export const SUPPLIER_PROVIDED = "SUPPLIER_PROVIDED";

export const SET_COSTS_DATE = "SET_COSTS_DATE";

export const GET_COSTS_ACTIVITY_DAILY = "GET_COSTS_ACTIVITY_DAILY";
export const GET_COSTS_ACTIVITY_WEEKLY = "GET_COSTS_ACTIVITY_WEEKLY";
export const GET_COSTS_ACTIVITY_MONTHLY = "GET_COSTS_ACTIVITY_MONTHLY";