
//* ANALYTICS

//AREA MANAGER
export const GET_AREA_MANAGER_ANALYTICS_LOCATIONS =
  "GET_AREA_MANAGER_ANALYTICS_LOCATIONS";
export const TOGGLE_ARREA_MANAGER_ANALYTICS_LOCATIONS =
  "TOGGLE_ARREA_MANAGER_ANALYTICS_LOCATIONS";
export const GET_AREA_MANAGER_ANALYTICS_COSTS =
  "GET_AREA_MANAGER_ANALYTICS_COSTS";
export const GET_AREA_MANAGER_ANALYTICS_DOORSTAFF =
  "GET_AREA_MANAGER_ANALYTICS_DOORSTAFF";
export const SET_AREA_MANAGER_ANALYTICS_DATE_FROM =
  "SET_AREA_MANAGER_ANALYTICS_DATE_FROM";
export const SET_AREA_MANAGER_ANALYTICS_DATE_TO =
  "SET_AREA_MANAGER_ANALYTICS_DATE_TO";

//PUB MANAGER
export const GET_DOORSTAFF_ANALYTICS = "GET_DOORSTAFF_ANALYTICS";
export const GET_COSTS_ANALYTICS = "GET_COSTS_ANALYTICS";
export const SET_DATE_FROM_ANALYTICS = "SET_DATE_FROM_ANALYTICS";
export const SET_DATE_TO_ANALYTICS = "SET_DATE_TO_ANALYTICS";
export const SET_CURRENT_TYPE = "SET_CURRENT_TYPE";

