
//*AUTHORISE

//GET
export const GET_AUTHORISE_DOORSTAFF = "GET_AUTHORISE_DOORSTAFF";
export const GET_AUTHORISE_COSTS = "GET_AUTHORISE_COSTS";

//CHECK
export const CHECK_AUTHORISE_DOORSTAFF = "CHECK_AUTHORISE_DOORSTAFF";
export const CHECK_AUTHORISE_COSTS = "CHECK_AUTHORISE_COSTS";
export const CHECK_ALL_AUTHORISE_DOORSTAFF = "CHECK_ALL_AUTHORISE_DOORSTAFF";
export const CHECK_ALL_AUTHORISE_COSTS = "CHECK_ALL_AUTHORISE_COSTS";

//UNCHECK
export const UNCHECK_AUTHORISE_DOORSTAFF = "UNCHECK_AUTHORISE_DOORSTAFF";
export const UNCHECK_AUTHORISE_COSTS = "UNCHECK_AUTHORISE_COSTS";
export const UNCHECK_ALL_AUTHORISE_DOORSTAFF =
  "UNCHECK_ALL_AUTHORISE_DOORSTAFF";
export const UNCHECK_ALL_AUTHORISE_COSTS = "UNCHECK_ALL_AUTHORISE_COSTS";

export const TOGGLE_MORE_ACTIONS_FOR_DOORSTAFF = "TOGGLE_MORE_ACTIONS_FOR_DOORSTAFF"
export const TOGGLE_MORE_ACTIONS_FOR_COSTS = "TOGGLE_MORE_ACTIONS_FOR_COSTS"
export const GET_DOORSTAFF_DISPUTED_NOTE_LIST = "GET_DOORSTAFF_DISPUTED_NOTE_LIST"
export const GET_COSTS_DISPUTED_NOTE_LIST = "GET_COSTS_DISPUTED_NOTE_LIST"

export const SET_DISPUTED_SIA_COUNT_MODAL = "SET_DISPUTED_SIA_COUNT_MODAL";
export const SET_DISPUTED_CC_COUNT_MODAL = "SET_DISPUTED_CC_COUNT_MODAL";
export const SET_DISPUTED_NOTE = "SET_DISPUTED_NOTE";
export const SET_DISPUTED_PAYMENT_ID = "SET_DISPUTED_PAYMENT_ID";