export const GET_RESPONSE = "GET_RESPONSE";
export const GET_BAD_RESPONSE = "GET_BAD_RESPONSE";
export const CLEAR_SUCCESS_MESSAGES = "CLEAR_SUCCESS_MESSAGES";
export const CLEAR_ERROR_MESSAGES = "CLEAR_ERROR_MESSAGES";
export const CLEAR_ALL_MESSAGES = "CLEAR_ALL_MESSAGES";
export const TOGGLE_DEBUG_CONSOLE = "TOGGLE_DEBUG_CONSOLE"
