export const GET_RESPONSE = "GET_RESPONSE";
export const ADD_ERROR_MESSAGE = "ADD_ERROR_MESSAGE";
export const CLEAR_SUCCESS_MESSAGES = "CLEAR_SUCCESS_MESSAGES";
export const CLEAR_ERROR_MESSAGES = "CLEAR_ERROR_MESSAGES";
export const CLEAR_ALL_MESSAGES = "CLEAR_ALL_MESSAGES";
