//*DOORSTAFF

//GET
export const GET_DOORSTAFF_LIST = "GET_DOORSTAFF_LIST";
export const GET_RECENT_DOORSTAFF = "GET_RECENT_DOORSTAFF";
export const GET_DISPUTED_DOORSTAFF = "GET_DISPUTED_DOORSTAFF";
export const GET_DOORSTAFF_POSITION_OPT = "GET_DOORSTAFF_POSITION_OPT";
export const GET_DOORSTAFF_SUPPLIER_OPT = "GET_DOORSTAFF_SUPPLIER_OPT";
export const GET_DOORSTAFF_RATE_OPT = "GET_DOORSTAFF_RATE_OPT";

export const TOGGLE_DOORSTAFF_TO_SIGN_OUT = "TOGGLE_DOORSTAFF_TO_SIGN_OUT";
export const SELECT_ALL_DOORSTAFF_TO_SIGN_OUT =
  "SELECT_ALL_DOORSTAFF_TO_SIGN_OUT";
export const DESELECT_ALL_DOORSTAFF_TO_SIGN_OUT =
  "DESELECT_ALL_DOORSTAFF_TO_SIGN_OUT";
export const SET_DOORSTAFF_SIGNOUT_TIME = "SET_DOORSTAFF_SIGNOUT_TIME";
export const SET_DOORSTAFF_SIGNOUT_DATE = "SET_DOORSTAFF_SIGNOUT_DATE";
export const SIGN_OFF_SELECTED_DOORSTAFF = "SIGN_OFF_SELECTED_DOORSTAFF";
export const SHOW_SIGN_OFF_MODAL = "SHOW_SIGN_OFF_MODAL";
export const HIDE_SIGN_OFF_MODAL = "HIDE_SIGN_OFF_MODAL";

//SET
export const SET_DOORSTAFF_ERROR_MESSAGE = "SET_DOORSTAFF_ERROR_MESSAGE";
export const SET_DOORSTAFF_POSITION = "SET_DOORSTAFF_POSITION";
export const SET_DOORSTAFF_SUPPLIER = "SET_DOORSTAFF_SUPPLIER";
export const SET_DOORSTAFF_RATE = "SET_DOORSTAFF_RATE";
export const SET_DOORSTAFF_START_DATE = "SET_DOORSTAFF_START_DATE";
export const SET_DOORSTAFF_START_TIME = "SET_DOORSTAFF_START_TIME";

//CLEAR
export const CLEAR_DOORSTAFF_ERROR_MESSAGE = "CLEAR_DOORSTAFF_ERROR_MESSAGE";

//*SIA

//GET
export const GET_SIA_DATA = "GET_SIA_DATA";

//SET
export const SET_SIA_NUMBER = "SET_SIA_NUMBER";
export const SET_SIA_ERROR_MESSAGE = "SET_SIA_ERROR_MESSAGE";


//CLEAR
export const CLEAR_SIA_ERROR_MESSAGE = "CLEAR_SIA_ERROR_MESSAGE";
export const CLEAR_SIA_DATA = "CLEAR_SIA_DATA";

export const GET_DOORSTAFF_SUMMARY_DAILY = "GET_DOORSTAFF_SUMMARY_DAILY";
export const GET_DOORSTAFF_SUMMARY_WEEKLY = "GET_DOORSTAFF_SUMMARY_WEEKLY";
export const GET_DOORSTAFF_SUMMARY_MONTHLY = "GET_DOORSTAFF_SUMMARY_MONTHLY";
export const GET_COSTS_DOORSTAFF_DAILY = "GET_COSTS_DOORSTAFF_DAILY";
export const GET_COSTS_DOORSTAFF_WEEKLY = "GET_COSTS_DOORSTAFF_WEEKLY";
export const GET_COSTS_DOORSTAFF_MONTHLY = "GET_COSTS_DOORSTAFF_MONTHLY";
