
//*HISTORY

//GET
export const GET_HISTORY_AUDIT_TYPE_OPT = "GET_HISTORY_AUDIT_TYPE_OPT";
export const GET_HISTORY_AUDIT_LOCATIONS_OPT =
  "GET_HISTORY_AUDIT_LOCATIONS_OPT";
export const GET_HISTORY_AUDIT_STAFF_OPT = "GET_HISTORY_AUDIT_STAFF_OPT";
export const GET_HISTORY_AUDIT_USER_OPT = "GET_HISTORY_AUDIT_USER_OPT";

//SET
export const SET_HISTORY_AUDIT_FROM_DATE = "SET_HISTORY_AUDIT_FROM_DATE";
export const SET_HISTORY_AUDIT_TO_DATE = "SET_HISTORY_AUDIT_TO_DATE";