
//*MODAL MESSAGE

export const SHOW_MODAL_MESSAGE = "SHOW_MODAL_MESSAGE";
export const HIDE_MODAL_MESSAGE = "HIDE_MODAL_MESSAGE";
export const SHOW_LOGOUT_MODAL = "SHOW_LOGOUT_MODAL";
export const HIDE_LOGOUT_MODAL = "HIDE_LOGOUT_MODAL";
export const SET_MODAL_MESSAGE_HEADER = "SET_MODAL_MESSAGE_HEADER";


//*MODAL PROMPT
export const SHOW_MODAL_PROMPT = "SHOW_MODAL_PROMPT";
export const HIDE_MODAL_PROMPT = "HIDE_MODAL_PROMPT";

export const RESET_MODAL_ACTIVITY = "RESET_MODAL_ACTIVITY";

//*MODAL ACTION
export const SHOW_ACTION_MODAL = "SHOW_ACTION_MODAL";
export const HIDE_ACTION_MODAL = "HIDE_ACTION_MODAL";