
//*SEARCH

//GET
export const GET_ACTIVITIES_SEARCH_LOCATIONS_GROUP_OPT =
  "GET_ACTIVITIES_SEARCH_LOCATIONS_GROUP_OPT";
export const GET_ACTIVITIES_SEARCH_SUPPLIERS_OPT =
  "GET_ACTIVITIES_SEARCH_SUPPLIERS_OPT";
export const GET_ACTIVITIES_SEARCH_PAYMENT_STATUS_GROUP_OPT =
  "GET_ACTIVITIES_SEARCH_PAYMENT_STATUS_GROUP_OPT";
export const GET_ACTIVITIES_SEARCH_LOCATIONS_OPT =
  "GET_ACTIVITIES_SEARCH_LOCATIONS_OPT";
export const GET_ACTIVITIES_SEARCH_PAYMENT_STATUS_OPT =
  "GET_ACTIVITIES_SEARCH_PAYMENT_STATUS_OPT";
export const GET_ACTIVITIES_SEARCH_STAFF_OPT =
  "GET_ACTIVITIES_SEARCH_STAFF_OPT";
export const GET_SEARCHED_ACTIVITES = "GET_SEARCHED_ACTIVITES";
export const GET_SEARCHED_COSTS = "GET_SEARCHED_COSTS";

//SET
export const SET_ACTIVITIES_SEARCH_FROM_DATE =
  "SET_ACTIVITIES_SEARCH_FROM_DATE";
export const SET_ACTIVITIES_SEARCH_TO_DATE = "SET_ACTIVITIES_SEARCH_TO_DATE";